package commands

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize the AgentOnRails config directory",
	Long: `Creates ~/.aor/ with the default directory structure and a starter
global config file. Safe to run multiple times — existing files are not overwritten.`,
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		home, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("cannot determine home directory: %w", err)
		}

		aorDir    := filepath.Join(home, ".aor")
		agentsDir := filepath.Join(aorDir, "agents")
		vaultsDir := filepath.Join(aorDir, "vaults")
		cfgPath   := filepath.Join(aorDir, "aor.yaml")

		for _, dir := range []string{agentsDir, vaultsDir} {
			if err := os.MkdirAll(dir, 0700); err != nil {
				return fmt.Errorf("create %s: %w", dir, err)
			}
		}

		createdCfg := false
		if _, err := os.Stat(cfgPath); os.IsNotExist(err) {
			if err := os.WriteFile(cfgPath, []byte(defaultGlobalConfig(aorDir)), 0600); err != nil {
				return fmt.Errorf("write config: %w", err)
			}
			createdCfg = true
		}

		fmt.Printf("  %s/\n", aorDir)
		fmt.Printf("  %s/\n", agentsDir)
		fmt.Printf("  %s/\n", vaultsDir)
		if createdCfg {
			fmt.Printf("  %s  (created)\n", cfgPath)
		} else {
			fmt.Printf("  %s  (already exists, not modified)\n", cfgPath)
		}
		fmt.Println()
		fmt.Println("Next steps:")
		fmt.Println("  aor agents create       # configure your first agent")
		fmt.Println("  aor start               # start the proxy daemon")
		return nil
	},
}

func defaultGlobalConfig(aorDir string) string {
	return fmt.Sprintf(`# AgentOnRails global configuration
# Generated by: aor init
# Edit this file to change daemon settings, facilitator URLs, and alert thresholds.

daemon:
  listen_addr: "127.0.0.1"
  log_level: "info"        # debug | info | warn | error
  audit_db:  "%s/audit.db"
  vault_dir: "%s/vaults"
  pid_file:  "%s/daemon.pid"

alerts:
  slack_webhook_url: ""    # optional — paste your Slack incoming webhook URL here
  budget_threshold_pct: 80 # alert when an agent's spend reaches 80%% of its limit

facilitators:
  # Coinbase-operated public facilitator — works for mainnet and testnet:
  x402: "https://x402.org/facilitator"
  # Enterprise Coinbase CDP endpoint (if you have CDP credentials):
  # x402: "https://api.cdp.coinbase.com/platform/v2/x402"
`, aorDir, aorDir, aorDir)
}

func init() {
	Root.AddCommand(initCmd)
}
